- name: deploy docker-compose with random mysql query
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - docker_service:
        project_src: compose
        scale:
          php: 10
      register: output


