version: '2'

services:
   db:
     build: ./mysql
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
   php:
    build: ./php
    restart: always
    volumes:
       - /var/log/apache2/error.log:/var/log/apache2/error.log
       - /var/log/apache2/access.log:/var/log/apache2/access.log
       - ./html:/var/www/html
    depends_on:
      - db
   lb:
    image: dockercloud/haproxy
    ports:
      - 8000:80
    links:
      - php
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
volumes:
    db_data:
